name: did-mailto
on:
  push:
    branches:
      - main
    paths:
      - 'packages/did-mailto/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/did-mailto.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/did-mailto/**'
      - 'packages/eslint-config-w3up/**'
      - '.github/workflows/did-mailto.yml'
      - 'pnpm-lock.yaml'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/did-mailto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: pnpm/action-setup@v4
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'
      - run: pnpm --filter '@web3-storage/did-mailto...' install
      - run: pnpm --filter '@web3-storage/did-mailto' lint
      - run: pnpm --filter '@web3-storage/did-mailto' test
