import type { TupleToUnion } from 'type-fest'
import * as Ucanto from '@ucanto/interface'
import { InferInvokedCapability, Link, DID } from '@ucanto/interface'
import { space, info, recover, recoverValidation } from './space.js'
import * as provider from './provider.js'
import * as consumer from './consumer.js'
import * as subscription from './subscription.js'
import * as customer from './customer.js'
import { top } from './top.js'
import { add, list, remove, store } from './store.js'
import * as UploadCaps from './upload.js'
import { claim, redeem } from './voucher.js'
import * as AccessCaps from './access.js'
import { Failure } from '@ucanto/validator/src/error.js'

export type { Link }

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface Unit {}
/**
 * failure due to a resource not having enough storage capacity.
 */
export interface InsufficientStorage {
  error: true
  name: 'InsufficientStorage'
  message: string
}

// Access
export type Access = InferInvokedCapability<typeof AccessCaps.access>

export type AccessRequest = InferInvokedCapability<typeof AccessCaps.request>
export type AccessRequestSuccess = Unit
export type AccessRequestFailure = Failure

export type AccessAuthorize = InferInvokedCapability<
  typeof AccessCaps.authorize
>

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export type AccessAuthorizeSuccess = Unit
export type AccessClaim = InferInvokedCapability<typeof AccessCaps.claim>
export interface AccessClaimSuccess {
  delegations: Record<string, Ucanto.ByteView<Ucanto.Delegation>>
}
export interface AccessClaimFailure {
  error: true
}

export type AccessDelegate = InferInvokedCapability<typeof AccessCaps.delegate>
export type AccessDelegateSuccess = unknown
export type AccessDelegateFailure = { error: true } | InsufficientStorage

export type AccessSession = InferInvokedCapability<typeof AccessCaps.session>
export type AccessConfirm = InferInvokedCapability<typeof AccessCaps.authorize>

// Provider
export type ProviderAdd = InferInvokedCapability<typeof provider.add>
export interface ProviderAddSuccess {}
export type ProviderAddFailure = Ucanto.Failure

// Consumer

export type Consumer = InferInvokedCapability<typeof consumer.consumer>

export type ConsumerAdd = InferInvokedCapability<typeof consumer.add>
export interface ConsumerAddSuccess {}
export interface ConsumerAddFailure extends Ucanto.Failure {}

export type ConsumerRemove = InferInvokedCapability<typeof consumer.remove>
export interface ConsumerRemoveSuccess {}
export interface ConsumerRemoveFailure extends Ucanto.Failure {}

export type ConsumerList = InferInvokedCapability<typeof consumer.list>
export interface ConsumerListSuccess {}
export interface ConsumerListFailure extends Ucanto.Failure {}

// Subscription

export type SubscriptionList = InferInvokedCapability<typeof subscription.list>
export interface SubscriptionListSuccess {
  // we will want to add add fields like other list operations
  // but for now this will do.
  results: SubscriptionRecord[]
}
export interface SubscriptionListFailure extends Ucanto.Failure {}

// Customer

export type CustomerAdd = InferInvokedCapability<typeof customer.add>
export interface CustomerAddSuccess {
  // Link of the invocation that successfully created a customer subscription
  cause: Link
}

export interface CustomerAddFailure extends Ucanto.Failure {}
export type CustomerList = InferInvokedCapability<typeof customer.list>

export interface Subscription {
  /**
   * CID of the invocation that created this subscription
   */
  cause: Link
  /**
   * Account that is billed for the subscription.
   */
  customer: DID
  /**
   * Provider that provides service to the customer.
   */
  provider: DID<'web'>
  /**
   * Identifier generated by the provider to identify this subscription.
   */
  order: Link
}
export interface SubscriptionRecord extends Subscription {
  inserted_at: Date
  updated_at: Date
}

export interface CustomerListSuccess {
  // we will want to add add fields like other list operations
  // but for now this will do.
  results: SubscriptionRecord[]
}

export interface CustomerListFailure extends Ucanto.Failure {}

// Space
export type Space = InferInvokedCapability<typeof space>
export type SpaceInfo = InferInvokedCapability<typeof info>
export type SpaceRecoverValidation = InferInvokedCapability<
  typeof recoverValidation
>
export type SpaceRecover = InferInvokedCapability<typeof recover>

// Voucher Protocol
export type VoucherRedeem = InferInvokedCapability<typeof redeem>
export type VoucherClaim = InferInvokedCapability<typeof claim>
// Upload
export type Upload = InferInvokedCapability<typeof UploadCaps.upload>
export type UploadAdd = InferInvokedCapability<typeof UploadCaps.add>
export type UploadRemove = InferInvokedCapability<typeof UploadCaps.remove>
export type UploadList = InferInvokedCapability<typeof UploadCaps.list>
// Store
export type Store = InferInvokedCapability<typeof store>
export type StoreAdd = InferInvokedCapability<typeof add>
export type StoreRemove = InferInvokedCapability<typeof remove>
export type StoreList = InferInvokedCapability<typeof list>
// Top
export type Top = InferInvokedCapability<typeof top>

export type Abilities = TupleToUnion<AbilitiesArray>

export type AbilitiesArray = [
  Top['can'],
  ProviderAdd['can'],
  Space['can'],
  SpaceInfo['can'],
  SpaceRecover['can'],
  SpaceRecoverValidation['can'],
  Upload['can'],
  UploadAdd['can'],
  UploadRemove['can'],
  UploadList['can'],
  Store['can'],
  StoreAdd['can'],
  StoreRemove['can'],
  StoreList['can'],
  VoucherClaim['can'],
  VoucherRedeem['can'],
  Access['can'],
  AccessAuthorize['can'],
  AccessSession['can']
]
